CREATE TABLE IF NOT EXISTS ACTEUR  (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(20) NOT NULL,
  LAST_NAME VARCHAR(20),
  PRIMARY KEY(ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS FILM (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  TITRE VARCHAR(20) NOT NULL,
  GENRE VARCHAR(20) NOT NULL,
  DESCRIPTION VARCHAR(255),
  ID_MAIN_ACTEUR BIGINT NOT NULL,
  FOREIGN KEY(ID_MAIN_ACTEUR) REFERENCES ACTEUR(ID),
  PRIMARY KEY(ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS FILM_SEC_ACTEURS(
ID_FILM BIGINT NOT NULL,
ID_ACTEUR BIGINT NOT NULL,
PRIMARY KEY (ID_FILM,ID_ACTEUR),
FOREIGN KEY(ID_FILM) REFERENCES FILM(ID),
FOREIGN KEY(ID_ACTEUR) REFERENCES ACTEUR(ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS APP_USER(
ID BIGINT NOT NULL AUTO_INCREMENT,
USERNAME VARCHAR(50) NOT NULL,
PRIMARY KEY (ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS REVIEW(
ID BIGINT NOT NULL AUTO_INCREMENT,
ID_FILM BIGINT NOT NULL,
ID_REVIEWER BIGINT NOT NULL,
MARK SMALLINT NOT NULL,
REVIEW_COMMENT VARCHAR(255),
PRIMARY KEY (ID),
FOREIGN KEY(ID_FILM) REFERENCES FILM(ID),
FOREIGN KEY(ID_REVIEWER) REFERENCES APP_USER(ID)
) ENGINE=InnoDB;



